# Generated by Django 5.0 on 2024-03-06 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obrasocial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=100)),
                ('observaciones', models.TextField(max_length=200)),
                ('obrasocial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obrasocial.obrasocial')),
            ],
        ),
    ]
