# Generated by Django 5.0 on 2024-03-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_paciente_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.CharField(max_length=8),
        ),
    ]
