# Generated by Django 5.0 on 2026-08-12 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrasocial', '0007_prestacionplan_honorario_fijo_medico_and_more'),
        ('paciente', '0006_paciente_activo_paciente_fecha_alta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='plan_obra_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='obrasocial.planobrasocial', verbose_name='Plan de Obra Social'),
        ),
    ]
