# Generated by Django 5.0 on 2026-09-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_paciente_plan_obra_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='numero_afiliado',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de afiliado'),
        ),
    ]
