# Generated by Django 5.0 on 2025-07-31 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0004_alter_paciente_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ecografia', 'Ecografía'), ('electrocardiograma', 'Electrocardiograma'), ('laboratorio', 'Laboratorio'), ('resonancia', 'Resonancia Magnética'), ('tomografia', 'Tomografía'), ('telemetria', 'Telemetría'), ('ecocardiograma', 'Ecocardiograma'), ('otros', 'Otros')], max_length=30)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='estudios/')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='paciente.paciente')),
            ],
        ),
    ]
