# Generated by Django 5.0 on 2026-02-27 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0001_initial'),
        ('historial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios', to='historial.consultamedica'),
        ),
    ]
