# Generated by Django 5.0 on 2026-07-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0002_estudio_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='tipo',
            field=models.CharField(choices=[('ecografia', 'Ecografía'), ('electrocardiograma', 'Electrocardiograma'), ('laboratorio', 'Laboratorio'), ('resonancia', 'Resonancia Magnética'), ('tomografia', 'Tomografía'), ('telemetria', 'Telemetría'), ('ecocardiograma', 'Ecocardiograma'), ('ergometria', 'Ergometria'), ('otros', 'Otros')], max_length=30),
        ),
    ]
