# Generated by Django 5.0 on 2026-05-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='centros',
            field=models.ManyToManyField(blank=True, to='core.centromedico'),
        ),
    ]
