# Generated by Django 5.0 on 2026-05-26 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perfilusuario_centros'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='centro_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_principales', to='core.centromedico'),
        ),
    ]
