# Generated by Django 5.0 on 2026-05-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_perfilusuario_centro_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('RECEPCION', 'Recepción'), ('MEDICO', 'Médico'), ('GERENCIA', 'Gerencia')], default='RECEPCION', max_length=20),
        ),
    ]
