# Generated by Django 5.0 on 2024-03-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medico',
        ),
    ]
