# Generated by Django 5.0 on 2026-07-20 22:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrasocial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obrasocial',
            options={'ordering': ['nombre'], 'verbose_name': 'Obra Social', 'verbose_name_plural': 'Obras Sociales'},
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='cuit',
            field=models.CharField(blank=True, max_length=13, verbose_name='CUIT'),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='domicilio',
            field=models.CharField(blank=True, max_length=250, verbose_name='Domicilio'),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='sigla',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Sigla'),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='obrasocial',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
        migrations.CreateModel(
            name='PlanObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('codigo', models.CharField(blank=True, max_length=30, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes', to='obrasocial.obrasocial', verbose_name='Obra Social')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['obra_social', 'nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='planobrasocial',
            constraint=models.UniqueConstraint(fields=('obra_social', 'nombre'), name='plan_unico_por_obra_social'),
        ),
    ]
