# Generated by Django 5.0 on 2026-07-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrasocial', '0002_alter_obrasocial_options_obrasocial_activa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrasocial',
            name='cartilla_online',
            field=models.URLField(blank=True, verbose_name='Cartilla Médica Online'),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='credenciales_online',
            field=models.URLField(blank=True, verbose_name='Descarga de Credenciales'),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='observaciones_portal',
            field=models.TextField(blank=True, verbose_name='Observaciones del Portal'),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='portal_afiliados',
            field=models.URLField(blank=True, verbose_name='Portal de Afiliados'),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='portal_autorizaciones',
            field=models.URLField(blank=True, verbose_name='Portal de Autorizaciones'),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='portal_prestadores',
            field=models.URLField(blank=True, verbose_name='Portal de Prestadores'),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='sitio_web',
            field=models.URLField(blank=True, verbose_name='Sitio Web'),
        ),
    ]
