# Generated by Django 5.0 on 2026-07-22 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrasocial', '0003_obrasocial_cartilla_online_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planobrasocial',
            options={'ordering': ['orden', 'codigo', 'nombre'], 'verbose_name': 'Plan', 'verbose_name_plural': 'Planes'},
        ),
        migrations.RemoveConstraint(
            model_name='planobrasocial',
            name='plan_unico_por_obra_social',
        ),
        migrations.RemoveField(
            model_name='planobrasocial',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='planobrasocial',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificación'),
        ),
        migrations.AddField(
            model_name='planobrasocial',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='planobrasocial',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='planobrasocial',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='planobrasocial',
            name='codigo',
            field=models.CharField(max_length=30, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='planobrasocial',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta'),
        ),
        migrations.AlterField(
            model_name='planobrasocial',
            name='obra_social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='obrasocial.obrasocial', verbose_name='Obra Social'),
        ),
        migrations.AddConstraint(
            model_name='planobrasocial',
            constraint=models.UniqueConstraint(fields=('obra_social', 'codigo'), name='plan_codigo_unico_por_obra_social'),
        ),
    ]
