# Generated by Django 5.0 on 2026-08-11 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclador', '0001_initial'),
        ('obrasocial', '0004_alter_planobrasocial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrasocial',
            name='usa_planes',
            field=models.BooleanField(default=False, verbose_name='¿Utiliza planes?'),
        ),
        migrations.CreateModel(
            name='PrestacionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Convenio')),
                ('fecha_vigencia_desde', models.DateField()),
                ('fecha_vigencia_hasta', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], default='ACTIVA', max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nomenclador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestaciones_convenio', to='nomenclador.nomencladorgeneral')),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestaciones', to='obrasocial.obrasocial')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestaciones', to='obrasocial.planobrasocial')),
            ],
            options={
                'verbose_name': 'Prestación',
                'verbose_name_plural': 'Prestaciones',
                'ordering': ['nomenclador__codigo'],
            },
        ),
        migrations.CreateModel(
            name='PrestacionPlanValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('moneda', models.CharField(default='ARS', max_length=10)),
                ('prestacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='obrasocial.prestacionplan')),
            ],
            options={
                'ordering': ['-vigente_desde'],
            },
        ),
        migrations.AddConstraint(
            model_name='prestacionplan',
            constraint=models.UniqueConstraint(fields=('obra_social', 'plan', 'nomenclador'), name='prestacion_unica_por_convenio'),
        ),
    ]
