# Generated by Django 5.0 on 2026-08-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrasocial', '0005_obrasocial_usa_planes_prestacionplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrasocial',
            name='es_particular',
            field=models.BooleanField(default=False, verbose_name='Es Particular'),
        ),
    ]
