# Generated by Django 5.0 on 2026-08-11 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrasocial', '0006_obrasocial_es_particular'),
        ('proveedores', '0003_liquidacionproveedor_cantidad_pagos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacionplan',
            name='honorario_fijo_medico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='prestacionplan',
            name='importe_proveedor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Importe Proveedor'),
        ),
        migrations.AddField(
            model_name='prestacionplan',
            name='porcentaje_consultorio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='prestacionplan',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='prestacionplan',
            name='porcentaje_medico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='prestacionplan',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestaciones_obras_sociales', to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='prestacionplan',
            name='tipo_calculo',
            field=models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('FIJO_MEDICO', 'Honorario fijo médico')], default='PORCENTAJE', max_length=20),
        ),
        migrations.AddField(
            model_name='prestacionplan',
            name='tipo_concepto',
            field=models.CharField(choices=[('CONSULTA', 'Consulta'), ('ESTUDIO', 'Estudio'), ('PRACTICA', 'Práctica'), ('CERTIFICADOS', 'Certificados')], default='CONSULTA', max_length=20),
        ),
    ]
