# Generated by Django 5.0 on 2026-08-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrasocial', '0007_prestacionplan_honorario_fijo_medico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacionplan',
            name='importe_coseguro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Importe Coseguro'),
        ),
        migrations.AddField(
            model_name='prestacionplan',
            name='tiene_coseguro',
            field=models.BooleanField(default=False, verbose_name='Tiene coseguro'),
        ),
    ]
