# Generated by Django 5.0 on 2026-08-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrasocial', '0008_prestacionplan_importe_coseguro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacionplan',
            name='importe_copago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Importe Copago'),
        ),
        migrations.AddField(
            model_name='prestacionplan',
            name='tiene_copago',
            field=models.BooleanField(default=False, verbose_name='Tiene copago'),
        ),
    ]
