# Generated by Django 5.0 on 2026-08-25 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0022_detallemovimientocaja_copago_cobrado_and_more'),
        ('obrasocial', '0009_prestacionplan_importe_copago_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='Mes')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PRESENTADO', 'Presentado'), ('COBRADO', 'Cobrado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=15, verbose_name='Estado')),
                ('fecha_presentacion', models.DateField(blank=True, null=True, verbose_name='Fecha de presentación')),
                ('numero_presentacion', models.CharField(blank=True, max_length=50, verbose_name='Número de presentación')),
                ('numero_factura', models.CharField(blank=True, max_length=50, verbose_name='Número de factura')),
                ('fecha_cobro', models.DateField(blank=True, null=True, verbose_name='Fecha de cobro')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='masters_obra_social_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='masters', to='obrasocial.obrasocial', verbose_name='Obra Social')),
            ],
            options={
                'verbose_name': 'Master de Obra Social',
                'verbose_name_plural': 'Masters de Obras Sociales',
                'ordering': ['-anio', '-mes', 'obra_social__nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleMasterObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('DEBITADO', 'Debitado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('importe_reconocido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Importe reconocido')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_incorporacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de incorporación')),
                ('fecha_resolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('detalle_movimiento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='detalle_master_obra_social', to='caja.detallemovimientocaja', verbose_name='Prestación')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='obrasocial.masterobrasocial', verbose_name='Master')),
            ],
            options={
                'verbose_name': 'Detalle Master de Obra Social',
                'verbose_name_plural': 'Detalles Master de Obra Social',
                'ordering': ['detalle_movimiento__fecha_prestacion', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='masterobrasocial',
            constraint=models.UniqueConstraint(fields=('obra_social', 'anio', 'mes'), name='master_unico_por_os_periodo'),
        ),
        migrations.AddConstraint(
            model_name='masterobrasocial',
            constraint=models.CheckConstraint(check=models.Q(('mes__gte', 1), ('mes__lte', 12)), name='master_mes_valido'),
        ),
    ]
