# Generated by Django 5.0 on 2026-08-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrasocial', '0010_masterobrasocial_detallemasterobrasocial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemasterobrasocial',
            name='estado_refacturacion',
            field=models.CharField(choices=[('NO_APLICA', 'No aplica'), ('PENDIENTE', 'Pendiente de refacturación'), ('PRESENTADA', 'Refacturación presentada'), ('ACEPTADA', 'Refacturación aceptada'), ('RECHAZADA', 'Refacturación rechazada')], default='NO_APLICA', max_length=20, verbose_name='Estado de refacturación'),
        ),
        migrations.AddField(
            model_name='detallemasterobrasocial',
            name='fecha_refacturacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de refacturación'),
        ),
        migrations.AddField(
            model_name='detallemasterobrasocial',
            name='importe_debitado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Importe debitado'),
        ),
        migrations.AddField(
            model_name='detallemasterobrasocial',
            name='importe_presentado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Importe presentado'),
        ),
        migrations.AddField(
            model_name='detallemasterobrasocial',
            name='motivo_debito',
            field=models.TextField(blank=True, verbose_name='Motivo del débito / rechazo'),
        ),
        migrations.AddField(
            model_name='detallemasterobrasocial',
            name='observacion_refacturacion',
            field=models.TextField(blank=True, verbose_name='Observación de refacturación'),
        ),
        migrations.AddField(
            model_name='detallemasterobrasocial',
            name='refacturable',
            field=models.BooleanField(default=False, verbose_name='¿Es refacturable?'),
        ),
        migrations.AlterField(
            model_name='detallemasterobrasocial',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de auditoría'), ('ACEPTADO', 'Aceptado'), ('DEBITO_PARCIAL', 'Débito parcial'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
    ]
