# Generated by Django 5.0 on 2026-09-12 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0022_detallemovimientocaja_copago_cobrado_and_more'),
        ('obrasocial', '0011_detallemasterobrasocial_estado_refacturacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemasterobrasocial',
            name='detalle_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refacturaciones', to='obrasocial.detallemasterobrasocial', verbose_name='Detalle de origen'),
        ),
        migrations.AddField(
            model_name='detallemasterobrasocial',
            name='fecha_ultima_gestion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última gestión'),
        ),
        migrations.AddField(
            model_name='detallemasterobrasocial',
            name='resuelto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_master_os_resueltos', to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por'),
        ),
        migrations.AlterField(
            model_name='detallemasterobrasocial',
            name='detalle_movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_master_obra_social', to='caja.detallemovimientocaja', verbose_name='Prestación'),
        ),
        migrations.AlterField(
            model_name='detallemasterobrasocial',
            name='estado_refacturacion',
            field=models.CharField(choices=[('NO_APLICA', 'No aplica'), ('PENDIENTE', 'Pendiente de refacturación'), ('PRESENTADA', 'Refacturación presentada'), ('ACEPTADA', 'Refacturación aceptada'), ('RECHAZADA', 'Refacturación rechazada'), ('CANCELADA', 'Cancelada / no refacturar')], default='NO_APLICA', max_length=20, verbose_name='Estado de refacturación'),
        ),
    ]
