# Generated by Django 5.0 on 2026-09-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrasocial', '0012_detallemasterobrasocial_detalle_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemasterobrasocial',
            name='detalle_observacion',
            field=models.TextField(blank=True, default='', verbose_name='Detalle de la observación'),
        ),
        migrations.AddField(
            model_name='detallemasterobrasocial',
            name='motivo_observacion',
            field=models.CharField(blank=True, choices=[('SIN_COBERTURA', 'Afiliado sin cobertura'), ('PLAN_INCORRECTO', 'Plan incorrecto / prestación no cubierta'), ('SIN_AUTORIZACION', 'Falta de autorización'), ('AUTORIZACION_INVALIDA', 'Autorización inválida o vencida'), ('FALTA_DOCUMENTACION', 'Falta de documentación'), ('CODIGO_INCORRECTO', 'Código de prestación incorrecto'), ('FUERA_CONVENIO', 'Prestación fuera de convenio'), ('DIFERENCIA_ARANCEL', 'Diferencia de arancel'), ('DUPLICADA', 'Prestación duplicada'), ('FUERA_DE_TERMINO', 'Presentación fuera de término'), ('FRECUENCIA_EXCEDIDA', 'Frecuencia / cantidad excedida'), ('DATOS_AFILIADO', 'Datos del afiliado incorrectos'), ('PROFESIONAL_NO_HABILITADO', 'Profesional no habilitado para la prestación'), ('AUDITORIA_MEDICA', 'Observación de auditoría médica'), ('ERROR_FACTURACION', 'Error de facturación'), ('OTRO', 'Otro motivo')], default='', max_length=40, verbose_name='Motivo de la observación'),
        ),
    ]
