# Generated by Django 5.0 on 2026-09-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrasocial', '0013_detallemasterobrasocial_detalle_observacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemasterobrasocial',
            name='fecha_liquidacion_honorario',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de liquidación del honorario'),
        ),
        migrations.AddField(
            model_name='detallemasterobrasocial',
            name='honorario_medico_liquidado',
            field=models.BooleanField(default=False, verbose_name='Honorario médico liquidado'),
        ),
        migrations.AddField(
            model_name='detallemasterobrasocial',
            name='honorario_medico_reconocido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Honorario médico reconocido'),
        ),
    ]
