# Generated by Django 5.0 on 2026-09-28 22:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrasocial', '0014_detallemasterobrasocial_fecha_liquidacion_honorario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='masterobrasocial',
            name='master_unico_por_os_periodo',
        ),
        migrations.AddField(
            model_name='masterobrasocial',
            name='tipo',
            field=models.CharField(choices=[('NORMAL', 'Presentación normal'), ('REFACTURACION', 'Refacturación')], default='NORMAL', max_length=20, verbose_name='Tipo de Master'),
        ),
        migrations.AddConstraint(
            model_name='masterobrasocial',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'NORMAL')), fields=('obra_social', 'anio', 'mes'), name='master_normal_unico_por_os_periodo'),
        ),
    ]
