# Generated by Django 5.0 on 2026-10-05 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obrasocial', '0015_remove_masterobrasocial_master_unico_por_os_periodo_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='masterobrasocial',
            name='master_normal_unico_por_os_periodo',
        ),
    ]
