# Generated by Django 5.0 on 2026-03-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnos',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ATENDIDO', 'Atendido'), ('AUSENTE', 'Ausente')], default='PENDIENTE', max_length=15),
        ),
    ]
