# Generated by Django 5.0 on 2026-03-25 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_medico_user'),
        ('turnos', '0002_turnos_estado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turnos',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='turnos',
            name='es_sobreturno',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DisponibilidadMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion_turno', models.IntegerField(default=20)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.medico')),
            ],
        ),
    ]
