# Generated by Django 5.0 on 2026-03-25 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_medico_user'),
        ('turnos', '0003_alter_turnos_unique_together_turnos_es_sobreturno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion_turno', models.IntegerField(default=20)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.medico')),
            ],
        ),
    ]
