# Generated by Django 5.0 on 2026-03-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0005_excepcionagenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='excepcionagenda',
            name='nueva_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='excepcionagenda',
            name='tipo',
            field=models.CharField(choices=[('CERRADO', 'No atiende'), ('MODIFICADO', 'Modificar horario'), ('REPROGRAMAR', 'Cambiar de día')], max_length=20),
        ),
    ]
