# Generated by Django 5.0 on 2026-04-01 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0008_consultorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamedico',
            name='consultorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='turnos.consultorio'),
        ),
    ]
