# Generated by Django 5.0 on 2026-05-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0009_agendamedico_consultorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobreturno',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ATENDIDO', 'Atendido'), ('AUSENTE', 'Ausente'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ATENDIDO', 'Atendido'), ('AUSENTE', 'Ausente'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15),
        ),
    ]
