# Generated by Django 5.0 on 2026-05-26 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perfilusuario_centros'),
        ('turnos', '0012_agendamedico_centro_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='excepcionagenda',
            name='centro_medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.centromedico'),
        ),
    ]
