# Generated by Django 5.0 on 2026-05-26 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perfilusuario_centros'),
        ('turnos', '0013_excepcionagenda_centro_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultorio',
            name='centro_medico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.centromedico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disponibilidadmedico',
            name='centro_medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.centromedico'),
        ),
        migrations.AddField(
            model_name='sobreturno',
            name='centro_medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.centromedico'),
        ),
        migrations.AlterField(
            model_name='consultorio',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='consultorio',
            unique_together={('centro_medico', 'numero')},
        ),
    ]
