# Generated by Django 5.0 on 2026-07-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0016_historialturno'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnos',
            name='tiempo_reservado',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='Tiempo reservado (minutos)'),
        ),
    ]
