# Generated by Django 5.0 on 2026-07-13 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_perfilusuario_rol'),
        ('medicos', '0003_medico_user'),
        ('turnos', '0017_turnos_tiempo_reservado'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo', models.CharField(choices=[('TURNO', 'Bloqueo por Turno'), ('MANUAL', 'Bloqueo Manual')], default='TURNO', max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=250)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('centro_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos_agenda', to='core.centromedico')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos_agenda', to='medicos.medico')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='turnos.turnos')),
            ],
            options={
                'verbose_name': 'Bloqueo de Agenda',
                'verbose_name_plural': 'Bloqueos de Agenda',
                'ordering': ['fecha', 'hora'],
                'unique_together': {('medico', 'fecha', 'hora')},
            },
        ),
    ]
