# Generated by Django 5.0 on 2026-07-14 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0018_bloqueoagenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobreturno',
            name='turno',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sobreturno', to='turnos.turnos'),
        ),
    ]
