# Generated by Django 5.0 on 2026-06-12 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_perfilusuario_rol'),
        ('medicos', '0003_medico_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total_honorarios', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_consultorio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_retenciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cantidad_prestaciones', models.IntegerField(default=0)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('centro_medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.centromedico')),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicos.medico')),
            ],
        ),
    ]
