# Generated by Django 5.0 on 2026-06-13 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_perfilusuario_rol'),
        ('honorarios', '0001_initial'),
        ('medicos', '0003_medico_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liquidacionmedica',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='liquidacionmedica',
            name='total_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='liquidacionmedica',
            name='centro_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_medicas', to='core.centromedico'),
        ),
        migrations.AlterField(
            model_name='liquidacionmedica',
            name='generado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_generadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='liquidacionmedica',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='medicos.medico'),
        ),
        migrations.AlterField(
            model_name='liquidacionmedica',
            name='total_honorarios',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
