# Generated by Django 5.0 on 2026-06-13 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0006_movimientocaja_retencion_motivo'),
        ('honorarios', '0002_alter_liquidacionmedica_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacionmedica',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de pago'), ('PAGADA', 'Pagada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='liquidacionmedica',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquidacionmedica',
            name='movimiento_egreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones_generadas', to='caja.movimientocaja'),
        ),
        migrations.AddField(
            model_name='liquidacionmedica',
            name='pagado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_pagadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
