# Generated by Django 5.0 on 2026-06-13 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0006_movimientocaja_retencion_motivo'),
        ('honorarios', '0003_liquidacionmedica_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacionmedica',
            name='movimiento_egreso',
        ),
        migrations.AddField(
            model_name='liquidacionmedica',
            name='cantidad_pagos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liquidacionmedica',
            name='total_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='liquidacionmedica',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de pago'), ('PARCIAL', 'Pago parcial'), ('PAGADA', 'Pagada')], default='PENDIENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='PagoLiquidacionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='honorarios.liquidacionmedica')),
                ('movimiento_caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caja.movimientocaja')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
