# Generated by Django 5.0 on 2026-08-21 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0021_detallemovimientocaja_coseguro_cobrado_and_more'),
        ('honorarios', '0004_remove_liquidacionmedica_movimiento_egreso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleLiquidacionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PARTICULAR', 'Particular'), ('COSEGURO', 'Coseguro'), ('OBRA_SOCIAL', 'Obra Social')], max_length=20, verbose_name='Tipo')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Importe liquidado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('detalle_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_liquidacion', to='caja.detallemovimientocaja', verbose_name='Detalle de prestación')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='honorarios.liquidacionmedica', verbose_name='Liquidación')),
            ],
            options={
                'verbose_name': 'Detalle de liquidación médica',
                'verbose_name_plural': 'Detalles de liquidaciones médicas',
                'ordering': ['id'],
            },
        ),
    ]
