# Generated by Django 5.0 on 2026-08-21 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honorarios', '0005_detalleliquidacionmedica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacionmedica',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_medicas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Generado por'),
        ),
    ]
