# Generated by Django 5.0 on 2026-08-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honorarios', '0006_liquidacionmedica_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleliquidacionmedica',
            name='tipo',
            field=models.CharField(choices=[('PARTICULAR', 'Particular'), ('COSEGURO', 'Coseguro'), ('COPAGO', 'Copago'), ('OBRA_SOCIAL', 'Obra Social')], max_length=20, verbose_name='Tipo'),
        ),
    ]
