# Generated by Django 5.0 on 2026-09-28 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honorarios', '0007_alter_detalleliquidacionmedica_tipo'),
        ('obrasocial', '0014_detallemasterobrasocial_fecha_liquidacion_honorario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleliquidacionmedica',
            name='detalle_master_obra_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_liquidacion_medica', to='obrasocial.detallemasterobrasocial', verbose_name='Detalle Master Obra Social'),
        ),
    ]
