# Generated by Django 5.0 on 2026-06-03 23:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_perfilusuario_rol'),
        ('paciente', '0006_paciente_activo_paciente_fecha_alta_and_more'),
        ('turnos', '0016_historialturno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Medio de pago',
                'verbose_name_plural': 'Medios de pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CajaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=20)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observacion_apertura', models.TextField(blank=True, null=True)),
                ('observacion_cierre', models.TextField(blank=True, null=True)),
                ('abierta_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_abiertas', to=settings.AUTH_USER_MODEL)),
                ('centro_medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_diarias', to='core.centromedico')),
                ('cerrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cajas_cerradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja diaria',
                'verbose_name_plural': 'Cajas diarias',
                'ordering': ['-fecha', 'centro_medico'],
                'unique_together': {('centro_medico', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], default='INGRESO', max_length=20)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('concepto', models.CharField(default='Consulta médica', max_length=200)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('ANULADO', 'Anulado')], default='ACTIVO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True, null=True)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja_anulados', to=settings.AUTH_USER_MODEL)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='caja.cajadiaria')),
                ('centro_medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to='core.centromedico')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja_creados', to=settings.AUTH_USER_MODEL)),
                ('medio_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='caja.mediopago')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to='paciente.paciente')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='turnos.turnos')),
            ],
            options={
                'verbose_name': 'Movimiento de caja',
                'verbose_name_plural': 'Movimientos de caja',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialMovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREADO', 'Creado'), ('ANULADO', 'Anulado'), ('EDITADO', 'Editado'), ('CIERRE_CAJA', 'Cierre de caja'), ('APERTURA_CAJA', 'Apertura de caja')], max_length=30)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='caja.cajadiaria')),
                ('centro_medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_caja', to='core.centromedico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_caja', to=settings.AUTH_USER_MODEL)),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='caja.movimientocaja')),
            ],
            options={
                'verbose_name': 'Historial de movimiento de caja',
                'verbose_name_plural': 'Historial de movimientos de caja',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
