# Generated by Django 5.0 on 2026-06-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        ('core', '0005_alter_perfilusuario_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cajadiaria',
            options={'ordering': ['-fecha', 'centro_medico', 'turno'], 'verbose_name': 'Caja diaria', 'verbose_name_plural': 'Cajas diarias'},
        ),
        migrations.AlterUniqueTogether(
            name='cajadiaria',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cajadiaria',
            name='turno',
            field=models.CharField(choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cajadiaria',
            unique_together={('centro_medico', 'fecha', 'turno')},
        ),
    ]
