# Generated by Django 5.0 on 2026-06-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_alter_cajadiaria_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('porcentaje_medico', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentaje_consultorio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='importe_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='importe_consultorio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='importe_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='importe_medico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='importe_neto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='retencion_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
