# Generated by Django 5.0 on 2026-06-12 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_conceptofacturacion_movimientocaja_importe_bruto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='concepto_facturacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='caja.conceptofacturacion'),
        ),
    ]
