# Generated by Django 5.0 on 2026-06-12 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_movimientocaja_concepto_facturacion'),
        ('honorarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='liquidacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='honorarios.liquidacionmedica'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='liquidado',
            field=models.BooleanField(default=False),
        ),
    ]
