# Generated by Django 5.0 on 2026-06-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_movimientocaja_liquidacion_movimientocaja_liquidado'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='retencion_motivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
