# Generated by Django 5.0 on 2026-06-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0006_movimientocaja_retencion_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptofacturacion',
            name='honorario_fijo_medico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='conceptofacturacion',
            name='tipo_calculo',
            field=models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('FIJO_MEDICO', 'Honorario fijo médico')], default='PORCENTAJE', max_length=20),
        ),
    ]
