# Generated by Django 5.0 on 2026-06-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0007_conceptofacturacion_honorario_fijo_medico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptofacturacion',
            name='porcentaje_consultorio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='conceptofacturacion',
            name='porcentaje_medico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
