# Generated by Django 5.0 on 2026-06-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0008_alter_conceptofacturacion_porcentaje_consultorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptofacturacion',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='conceptofacturacion',
            name='importe_proveedor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='conceptofacturacion',
            name='tipos_conceptos',
            field=models.CharField(choices=[('CONSULTA', 'Consulta'), ('ESTUDIO', 'Estudio'), ('PRACTICA', 'Práctica'), ('CERTIFICADOS', 'Certificados')], default='CONSULTA', max_length=20),
        ),
        migrations.AddField(
            model_name='conceptofacturacion',
            name='tipos_proveedores',
            field=models.CharField(blank=True, choices=[('PATOLOGO', 'Patólogo'), ('BIOQUIMICO', 'Bioquímico')], default='', max_length=20),
        ),
    ]
