# Generated by Django 5.0 on 2026-07-02 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0009_conceptofacturacion_codigo_and_more'),
        ('nomenclador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conceptofacturacion',
            options={'ordering': ['nomenclador__descripcion'], 'verbose_name': 'Concepto de Facturación', 'verbose_name_plural': 'Conceptos de Facturación'},
        ),
        migrations.RenameField(
            model_name='conceptofacturacion',
            old_name='tipos_conceptos',
            new_name='tipo_concepto',
        ),
        migrations.RemoveField(
            model_name='conceptofacturacion',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='conceptofacturacion',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='conceptofacturacion',
            name='tipos_proveedores',
        ),
        migrations.AddField(
            model_name='conceptofacturacion',
            name='importe_particular',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Importe Particular'),
        ),
        migrations.AddField(
            model_name='conceptofacturacion',
            name='nomenclador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='particular', to='nomenclador.nomencladorgeneral'),
        ),
        migrations.AddField(
            model_name='conceptofacturacion',
            name='tipo_proveedor',
            field=models.CharField(blank=True, choices=[('', '---------'), ('PATOLOGO', 'Patólogo'), ('BIOQUIMICO', 'Bioquímico')], default='', max_length=20),
        ),
    ]
