# Generated by Django 5.0 on 2026-07-07 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caja", "0011_agregar_importe_particular"),
        ("honorarios", "0004_remove_liquidacionmedica_movimiento_egreso_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetalleMovimientoCaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, verbose_name="Código")),
                (
                    "descripcion",
                    models.CharField(max_length=250, verbose_name="Descripción"),
                ),
                (
                    "tipo_concepto",
                    models.CharField(
                        choices=[
                            ("CONSULTA", "Consulta"),
                            ("ESTUDIO", "Estudio"),
                            ("PRACTICA", "Práctica"),
                            ("CERTIFICADOS", "Certificados"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de prestación",
                    ),
                ),
                (
                    "fecha_prestacion",
                    models.DateField(verbose_name="Fecha de la prestación"),
                ),
                (
                    "cantidad",
                    models.PositiveIntegerField(default=1, verbose_name="Cantidad"),
                ),
                (
                    "tipo_calculo",
                    models.CharField(
                        choices=[
                            ("PORCENTAJE", "Porcentaje"),
                            ("FIJO_MEDICO", "Honorario fijo médico"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de cálculo",
                    ),
                ),
                (
                    "porcentaje_iva",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="IVA (%)",
                    ),
                ),
                (
                    "porcentaje_medico",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Honorario Médico (%)",
                    ),
                ),
                (
                    "porcentaje_consultorio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Consultorio (%)",
                    ),
                ),
                (
                    "honorario_fijo_medico",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Honorario fijo",
                    ),
                ),
                (
                    "tipo_proveedor",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "---------"),
                            ("PATOLOGO", "Patólogo"),
                            ("BIOQUIMICO", "Bioquímico"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Proveedor",
                    ),
                ),
                (
                    "importe_proveedor",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Importe proveedor",
                    ),
                ),
                (
                    "importe",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Importe Bruto"
                    ),
                ),
                (
                    "importe_iva",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="IVA"
                    ),
                ),
                (
                    "importe_neto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Importe Neto",
                    ),
                ),
                (
                    "importe_medico",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Honorario Médico",
                    ),
                ),
                (
                    "importe_consultorio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Importe Consultorio",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("LIQUIDADO", "Liquidado"),
                            ("ANULADO", "Anulado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=1, verbose_name="Orden")),
                (
                    "observacion",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Observación"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "concepto_facturacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="caja.conceptofacturacion",
                        verbose_name="Prestación",
                    ),
                ),
                (
                    "liquidacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detalles",
                        to="honorarios.liquidacionmedica",
                        verbose_name="Liquidación",
                    ),
                ),
                (
                    "movimiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="caja.movimientocaja",
                        verbose_name="Movimiento de Caja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Movimiento",
                "verbose_name_plural": "Detalles de Movimiento",
                "ordering": ["orden", "id"],
            },
        ),
    ]
