# Generated by Django 5.0 on 2026-07-07 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caja", "0012_detallemovimientocaja"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetalleMedioPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "importe",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Importe"
                    ),
                ),
                ("observacion", models.CharField(blank=True, max_length=250)),
                ("orden", models.PositiveIntegerField(default=1)),
                (
                    "medio_pago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="caja.mediopago",
                        verbose_name="Medio de Pago",
                    ),
                ),
                (
                    "movimiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles_medios_pago",
                        to="caja.movimientocaja",
                        verbose_name="Movimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle Medio de Pago",
                "verbose_name_plural": "Detalles Medios de Pago",
                "ordering": ["orden", "id"],
            },
        ),
    ]
