# Generated by Django 5.0 on 2026-07-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caja", "0013_detallemediopago"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movimientocaja",
            name="medio_pago",
        ),
    ]
