# Generated by Django 5.0 on 2026-07-15 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0014_remove_movimientocaja_medio_pago'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptofacturacion',
            name='tipo_proveedor',
        ),
        migrations.RemoveField(
            model_name='detallemovimientocaja',
            name='tipo_proveedor',
        ),
        migrations.AddField(
            model_name='conceptofacturacion',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conceptos', to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='detallemovimientocaja',
            name='nombre_proveedor',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='detallemovimientocaja',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.proveedor'),
        ),
        migrations.AlterField(
            model_name='conceptofacturacion',
            name='importe_proveedor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Importe Proveedor'),
        ),
        migrations.AlterField(
            model_name='detallemovimientocaja',
            name='importe_proveedor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Importe Proveedor'),
        ),
    ]
