# Generated by Django 5.0 on 2026-07-15 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0015_remove_conceptofacturacion_tipo_proveedor_and_more'),
        ('proveedores', '0002_liquidacionproveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemovimientocaja',
            name='liquidacion_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles', to='proveedores.liquidacionproveedor', verbose_name='Liquidación Proveedor'),
        ),
    ]
