# Generated by Django 5.0 on 2026-08-12 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0016_detallemovimientocaja_liquidacion_proveedor'),
        ('obrasocial', '0007_prestacionplan_honorario_fijo_medico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemovimientocaja',
            name='prestacion_obra_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_caja', to='obrasocial.prestacionplan', verbose_name='Prestación Obra Social'),
        ),
    ]
