# Generated by Django 5.0 on 2026-07-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0016_detallemovimientocaja_liquidacion_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptofacturacion',
            name='tipo_concepto',
            field=models.CharField(choices=[('CONSULTA', 'Consulta'), ('ESTUDIO', 'Estudio'), ('PRACTICA', 'Práctica'), ('CERTIFICADOS', 'Certificados'), ('DEPILACION', 'Depilacion')], default='CONSULTA', max_length=20),
        ),
        migrations.AlterField(
            model_name='detallemovimientocaja',
            name='tipo_concepto',
            field=models.CharField(choices=[('CONSULTA', 'Consulta'), ('ESTUDIO', 'Estudio'), ('PRACTICA', 'Práctica'), ('CERTIFICADOS', 'Certificados'), ('DEPILACION', 'Depilacion')], max_length=20, verbose_name='Tipo de prestación'),
        ),
    ]
