# Generated by Django 5.0 on 2026-08-19 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0017_detallemovimientocaja_prestacion_obra_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallemovimientocaja',
            name='concepto_facturacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='caja.conceptofacturacion', verbose_name='Prestación'),
        ),
    ]
