# Generated by Django 5.0 on 2026-07-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0017_alter_conceptofacturacion_tipo_concepto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='es_depilacion',
            field=models.BooleanField(default=False, verbose_name='Corresponde a Depilación'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='tipo_egreso_depilacion',
            field=models.CharField(blank=True, choices=[('OPERADORA', 'Operadora'), ('ALQUILER', 'Alquiler de máquina')], max_length=20, null=True, verbose_name='Tipo de egreso de depilación'),
        ),
    ]
