# Generated by Django 5.0 on 2026-08-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0019_movimientocaja_es_depilacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemovimientocaja',
            name='importe_coseguro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Importe coseguro'),
        ),
        migrations.AddField(
            model_name='detallemovimientocaja',
            name='tiene_coseguro',
            field=models.BooleanField(default=False, verbose_name='Tiene coseguro'),
        ),
    ]
