# Generated by Django 5.0 on 2026-08-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0020_detallemovimientocaja_importe_coseguro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemovimientocaja',
            name='coseguro_cobrado',
            field=models.BooleanField(default=False, verbose_name='Coseguro cobrado'),
        ),
        migrations.AddField(
            model_name='detallemovimientocaja',
            name='coseguro_liquidado',
            field=models.BooleanField(default=False, verbose_name='Coseguro liquidado'),
        ),
        migrations.AddField(
            model_name='detallemovimientocaja',
            name='fecha_cobro_obra_social',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de cobro obra social'),
        ),
        migrations.AddField(
            model_name='detallemovimientocaja',
            name='honorario_os_liquidado',
            field=models.BooleanField(default=False, verbose_name='Honorario de obra social liquidado'),
        ),
        migrations.AddField(
            model_name='detallemovimientocaja',
            name='obra_social_cobrada',
            field=models.BooleanField(default=False, verbose_name='Obra social cobrada'),
        ),
    ]
