# Generated by Django 5.0 on 2026-08-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0021_detallemovimientocaja_coseguro_cobrado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemovimientocaja',
            name='copago_cobrado',
            field=models.BooleanField(default=False, verbose_name='Copago cobrado'),
        ),
        migrations.AddField(
            model_name='detallemovimientocaja',
            name='copago_liquidado',
            field=models.BooleanField(default=False, verbose_name='Copago liquidado'),
        ),
        migrations.AddField(
            model_name='detallemovimientocaja',
            name='importe_copago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Importe copago'),
        ),
        migrations.AddField(
            model_name='detallemovimientocaja',
            name='tiene_copago',
            field=models.BooleanField(default=False, verbose_name='Tiene copago'),
        ),
    ]
