# Generated by Django 5.0 on 2026-09-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0022_detallemovimientocaja_copago_cobrado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemovimientocaja',
            name='honorario_reconocido_obra_social',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Honorario médico reconocido por Obra Social'),
        ),
        migrations.AddField(
            model_name='detallemovimientocaja',
            name='importe_reconocido_obra_social',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Importe reconocido por Obra Social'),
        ),
    ]
