# Generated by Django 5.0 on 2024-03-29 11:19

import agendas.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0002_alter_medico_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(help_text='Introduzca una fecha para el calendario', validators=[agendas.models.validar_dia])),
                ('horario', models.CharField(choices=[('1', '07:00 hasta 07:30'), ('2', '07:30 hasta 08:00'), ('3', '08:00 hasta 08:30'), ('4', '08:30 hasta 09:00'), ('5', '09:00 hasta 09:30'), ('6', '09:30 hasta 10:00'), ('7', '10:00 hasta 10:30'), ('8', '10:30 hasta 11:00'), ('9', '11:00 hasta 11:30'), ('10', '11:30 hasta 12:00'), ('11', '12:00 hasta 12:30'), ('12', '12:30 hasta 13:00'), ('13', '13:00 hasta 13:30'), ('14', '13:30 hasta 14:00'), ('15', '14:00 hasta 14:30'), ('16', '14:30 hasta 15:00'), ('17', '15:00 hasta 15:30'), ('18', '15:30 hasta 16:00'), ('19', '16:00 hasta 16:30'), ('20', '16:30 hasta 17:00'), ('21', '17:00 hasta 17:30'), ('22', '17:30 hasta 18:00'), ('23', '18:00 hasta 18:30'), ('24', '18:30 hasta 19:00'), ('25', '19:00 hasta 19:30'), ('26', '19:30 hasta 20:00'), ('27', '20:00 hasta 20:30'), ('28', '20:30 hasta 21:00')], max_length=10)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='medicos.medico')),
            ],
            options={
                'unique_together': {('horario', 'dia')},
            },
        ),
    ]
