# Generated by Django 5.0 on 2024-03-29 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0001_initial'),
        ('paciente', '0004_alter_paciente_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendas',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
    ]
