# Generated by Django 5.0 on 2024-03-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0002_agendas_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendas',
            name='atendido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agendas',
            name='mes',
            field=models.CharField(default='Enero', help_text='Mes del año', max_length=10),
        ),
        migrations.AlterField(
            model_name='agendas',
            name='dia',
            field=models.DateField(help_text='Introduzca una fecha para el calendario'),
        ),
    ]
