# Generated by Django 5.0 on 2024-03-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0003_agendas_atendido_agendas_mes_alter_agendas_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendas',
            name='mes',
            field=models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Enero'), ('Marzo', 'Enero'), ('Abril', 'Enero'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=10),
        ),
    ]
