# Generated by Django 5.0 on 2025-07-28 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0004_alter_agendas_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendas',
            name='mes',
        ),
    ]
