# Generated by Django 5.0 on 2026-03-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamedica',
            name='examen_fisico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
