# Generated by Django 5.0 on 2026-03-09 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0002_consultamedica_examen_fisico'),
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamedica',
            name='turno',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulta', to='turnos.turnos'),
        ),
    ]
