# Generated by Django 5.0 on 2026-03-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0003_consultamedica_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamedica',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('FINALIZADA', 'Finalizada')], default='BORRADOR', max_length=15),
        ),
    ]
