# Generated by Django 5.0 on 2026-05-14 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0004_consultamedica_estado'),
        ('turnos', '0009_agendamedico_consultorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamedica',
            name='sobreturno',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulta', to='turnos.sobreturno'),
        ),
    ]
