# Generated by Django 5.0 on 2026-06-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0005_consultamedica_sobreturno'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='antecedentes_alergicos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='antecedentes_patologicos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='antecedentes_quirurgicos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='antecedentes_toxicos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='medicacion_base',
            field=models.TextField(blank=True, null=True),
        ),
    ]
