# Generated by Django 5.0 on 2026-07-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('LABORATORIO', 'Laboratorio'), ('PATOLOGIA', 'Patología'), ('DIAGNOSTICO', 'Centro de Diagnóstico'), ('CARDIOLOGIA', 'Cardiología'), ('RADIOLOGIA', 'Radiología'), ('OTRO', 'Otro')], max_length=30)),
                ('razon_social', models.CharField(blank=True, max_length=200)),
                ('cuit', models.CharField(blank=True, max_length=15)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('banco', models.CharField(blank=True, max_length=100)),
                ('cbu', models.CharField(blank=True, max_length=30)),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
    ]
