# Generated by Django 5.0 on 2026-07-16 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0016_detallemovimientocaja_liquidacion_proveedor'),
        ('proveedores', '0002_liquidacionproveedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacionproveedor',
            name='cantidad_pagos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liquidacionproveedor',
            name='pagado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_proveedor_pagadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liquidacionproveedor',
            name='total_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='liquidacionproveedor',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Pago Parcial'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='liquidacionproveedor',
            name='generado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_proveedor_generadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PagoLiquidacionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='proveedores.liquidacionproveedor')),
                ('movimiento_caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_proveedor', to='caja.movimientocaja')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de Liquidación',
                'verbose_name_plural': 'Pagos de Liquidaciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
